import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistMono.variable} dark overflow-hidden antialiased`}
      >
        <Header />
        <div className="flex h-[calc(100vh-4rem)] gap-4 p-4">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
